### ISSUE TITLE
Report page graphics

### ISSUE THREAD

**Issue by lorenzoPrimi** [measurement-kit/netprobe-ios#33]
Would be nice to make a template for every test result and use the json to populate the template with relative data.
This is a mockup drawn by me and @hellais 
![mk](https://cloud.githubusercontent.com/assets/1616097/16226086/1eef3408-37aa-11e6-93db-6d42ed891a34.png)

Firstly we need to understand how to generate a result html mixing template page and json data (I prefer to do everything locally, so there is no webserver and no php)
Then we need to draw a nice template according to this schema.

The template is made of three parts, test meta data, test description and test results. The first two are the same for every test, the third change based on the test. 
In this template we drawn results for web connectivity and invalid request line.
"More info" buttons are used to show more details about the result of the test, initially is better to have the block below hidden.

Let's get the ideas flowing!

**Comment by bassosimone** [comment]
I have been a long time subscriber to the party that we can add a webserver, yet I recognized that if we can get away without it, and we demonstrate future viability, we are better off.

So, if I understand correctly the terms of the problem, we have an HTML file including bits of JavaScript and CSS, all amalgamated, stored on disk. What we would like to do, at this point, would be to load that file and somehow insert into it the whole test result. And then pass the result of a WebView-ish object that will show it to the user. Correct?

In that case, and considering that MK has the capability of serializing to JSON, I believe the following could be a reasonable way to perform this task:

1. write amalgamated HTML file on disk with a placeholder instead of the JSON code, e.g.

```HTML
<html>
 <head>
  <script>
   // ...
   var RESULTS = {};
  </script>
```

2. in ObjC or Java (perhaps not as part of the apps but as part of the `-android` and the to-be-created `-ios` repositories) load from disk the HTML file and the serialized JSON file

3. string replace `var RESULTS = []` with the JSON file (which *actually* is an array of JSON objects)

4. pass the resulting buffer to the WebView

What worries me here is the size of the JSON. For certain OONI tests, where basically OONi does `map()` over a not-so-short array of URLs, the JSON can be very large (tens of megabytes).

This is to say that, if we have some sort of iterator-ish API, we can pull only the bits we need from disk, whereas if we are to load all the result in one single operation, this would be less scalable.

A possible workaround would be to store the results of a test as a directory and each entry as a file within such directory, so that moving from one entry to the next one would trigger an on-disk read of the specific bit of file, thus basically emulating what we would get from a REST API.

@lorenzoPrimi @hellais, what do you think?

**Comment by lorenzoPrimi** [comment]
I totally agree with @bassosimone , in fact this was my first idea. Firstly because it doesn't require a web server, but also because I think we can write some code that is not really heavy. 
A solution can be to generate the result webpage in background after a test is done and save the resulting html on disk, so for each test it has to be generated only once.

Don't know how much will be scalable, but for now I think it's the right way.

**Comment by hellais** [comment]
Looking into this a big another possible option would be that of creating a special `<script>` tag that is injected using the webkit view.

This tag could contain something like:

```
<script type="application/json" id="measurement">
{
"something": "bar"
}
</script>
```

Then it can be accessed by the web application logic with something like:

```
var measurement = JSON.parse($('#measurement').html());
```

The HTML and JS assets can be all the same for every measurement (not have to generate them for every measurement result) and a runtime we can inject them:

* On iOS with `WKUserScript` (https://developer.apple.com/library/ios/documentation/WebKit/Reference/WKUserScript_Ref/index.html)
(see also: http://stackoverflow.com/questions/26573528/inject-a-javascript-code-in-webview-ios)

* On Android with the situation is a bit messier and it seems like there is no equivalent way of creating a `<script>` tag. All things related to evaluating javascript use the hack of calling `WebView.loadurl("javascript:")`. Maybe it's good to see if there is some better way of doing this there.

I am quite against, though, the approach of duplicating the HTML and JS resources for every measurement page we need to render.

**Comment by lorenzoPrimi** [comment]
I like this approach, as we can generate on the fly the result page without having to save it on disk.
I will try something with current json. Do we already have a result template or something similar?

**Comment by hellais** [comment]
So I think I have found a better way of doing this inside of Android.

Apparently there is an API called `addJavascriptInterface` (https://developer.android.com/reference/android/webkit/WebView.html#addJavascriptInterface(java.lang.Object, java.lang.String)) that allows you to inject a `Java` object into the content of a javascript page.

Here is what would be required to make this work in the various platforms:

### Android

```
import java.io.File;
import java.io.FileReader;
import java.io.IOException;

public class InjectedJSON {
    private String jsonData;

    public InjectedJSON(String file_path) {
       jsonData = new String(Files.readAllBytes(file_path));
    }

    @JavascriptInterface
    public String get() {
       return jsonData;
    }
}

public class MainActivity extends Activity {
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        WebView wv = (WebView) findViewById(R.id.myWebView);
        wv.getSettings().setJavaScriptEnabled(true);
        wv.addJavascriptInterface(new InjectedJSON("path/to/measurement.json"), "MeasurementJSON");
        wv.loadUrl("file:///android_asset/index.html");
    }
}
```

The key points here are that you decorate the methods to be used in javascript with `@JavascriptInterface`, you call `setJavaScriptEnabled` with true and inject a new instance of the object with `addJavascriptInterface`.

### iOS

On iOS something along the lines of this should work:
```
_webConfig = [[WKWebViewConfigurationalloc]init];

WKUserContentController* userController = [[WKUserContentControlleralloc]init];

NSString* MeasurementJSON = [stringWithFormat:@"\n var MeasurementJSON = {  \n"
                      "get: function() {  \n"
                      "return "
                      "'{THE JSON DOCUMENT}';"
                      "   } \n"
                      "}"]

WKUserScript* userScript = [[WKUserScriptalloc]initWithSource:MeasurementJSON
                           injectionTime: WKUserScriptInjectionTimeAtDocumentStart
                           forMainFrameOnly:NO];
[userController addUserScript:userScript];
_webConfig.userContentController= userController;
```

The  key elements here are to register the variable `MeasurementJSON` inside of the global scope to have the same exact interface as the one on android. To ensure that the script is injected at `WKUserScriptInjectionTimeAtDocumentStart` so that we have this variable registered before the javascript loads.

### Javascript side

The javascript side of the code should then be implemented in a way like the following:

```js
MeasurementSummaryController.$inject = ['$stateParams', '$scope', '$http', '$window'];
function MeasurementSummaryController($stateParams, $scope, $http) {
   var measurementFromNetwork = function() {
     $http.get('/api/measurement/'+$stateParams.measurementId)
      .then(function(response){
        $scope.measurements = response.data;
      }, function(error){
        console.log(error);
      });
   }
   var measurementFromInjectedObject = function() {
     $scope.measurements = MeasurementJSON.get();
   }

   if (typeof MeasurementJSON != undefined) {
     measurementFromInjectedObject();
   } else {
     measurementFromNetwork();
   }
}

```

I am going to write up a PoC for this approach that should be cross platform between Android, iOS and the desktop version of the app and we can try it out to see if it works as expected.

**Comment by bassosimone** [comment]
I guess the recently merge of #34 implies we can close this issue, isn't it @lorenzoPrimi?
